language: java
sudo: true
dist: trusty

before_install:
    # Add repos
    - sudo apt-add-repository "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    # Remove "deb-src" repos added from apt-add-repository, because it doesn't exist online
    - sudo sed -i s/deb-src.*google.*//g /etc/apt/sources.list
    # Add apt-keys for checking the packages
    - wget -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    # Mke sure
    - sudo apt-get update -qq
    # Install the browsers
    - sudo apt-get install -y google-chrome-stable
    # start xvfb
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

install:
    # operachromiumdriver does not work with xvfb, see: https://github.com/operasoftware/operachromiumdriver/issues/26
    - mvn -Dheadless=true clean verify
